name: Linux

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'docs/**'
      - STATUS
      - CHANGES
      - changes-entries/*
    tags:
      - 2.*
  pull_request:
    branches: [ "trunk", "2.4.x" ]
    paths-ignore:
      - 'docs/**'
      - STATUS
      - CHANGES
      - changes-entries/*

env:
  MARGS: "-j2"
  CFLAGS: "-g"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: 
       #   # -------------------------------------------------------------------------
       #  - name: Empty APLOGNO() test
       #     env: |
       #       SKIP_TESTING=1
       #       TEST_LOGNO=1
          # -------------------------------------------------------------------------
       #   - name: Default
          # -------------------------------------------------------------------------
       #   - name: All-static modules
       #     config: --enable-mods-static=reallyall
          # -------------------------------------------------------------------------
       #   - name: Prefork MPM, all-modules (except cgid)
       #     config: --enable-mods-shared=reallyall --with-mpm=prefork --disable-cgid
          # -------------------------------------------------------------------------
       #   - name: Worker MPM, all-modules
       #     config: --enable-mods-shared=reallyall --with-mpm=worker
          # -------------------------------------------------------------------------
       #   - name: Shared MPMs, all-modules
       #     config: --enable-mods-shared=reallyall --enable-mpms-shared=all
          # -------------------------------------------------------------------------
       #   - name: Event MPM, all-modules, mod_cgid only
       #     config: --enable-mods-shared=reallyall --with-mpm=event --disable-cgi
          # -------------------------------------------------------------------------
       #   - name: Event MPM, all-modules, no CMSG_DATA
       #     config: --enable-mods-shared=reallyall --with-mpm=event ac_cv_have_decl_CMSG_DATA=no
          # -------------------------------------------------------------------------
       #   - name: Default, all-modules + install
       #     config: --enable-mods-shared=reallyall
       #     env: |
       #       TEST_INSTALL=1
       #       APACHE_TEST_EXTRA_ARGS=-v
          - name: Shared MPMs (event), pool-debug, SSL/TLS variants
            config: --enable-mods-shared=reallyall --enable-mpms-shared=all --with-mpm=event
            env: |
              APR_VERSION=1.7.x
              APR_CONFIG="--enable-pool-debug"
              APU_VERSION=1.7.x
              APU_CONFIG="--with-crypto --with-ldap"
              TEST_MALLOC=1
              TEST_SSL=1
              CLEAR_CACHE=1
         # -------------------------------------------------------------------------
          - name: Shared MPMs (worker), pool-debug, SSL/TLS variants
            config: --enable-mods-shared=reallyall --enable-mpms-shared=all --with-mpm=worker
            env: |
              APR_VERSION=1.7.x
              APR_CONFIG="--enable-pool-debug"
              APU_VERSION=1.7.x
              APU_CONFIG="--with-crypto --with-ldap"
              TEST_MALLOC=1
              TEST_SSL=1
              CLEAR_CACHE=1
          # --------------------------------------------------------------------------
          - name: Shared MPMs (prefork), pool-debug, SSL/TLS variants
            config: --enable-mods-shared=reallyall --enable-mpms-shared=all --with-mpm=prefork
            env: |
              APR_VERSION=1.7.x
              APR_CONFIG="--enable-pool-debug"
              APU_VERSION=1.7.x
              APU_CONFIG="--with-crypto --with-ldap"
              TEST_MALLOC=1
              TEST_SSL=1
              CLEAR_CACHE=1
         # -------------------------------------------------------------------------
 
          - name: APR 1.7.4, APR-util 1.6.3, LDAP
            config: --enable-mods-shared=reallyall
            pkgs: ldap-utils
            env: |
              APR_VERSION=1.7.4
              APU_VERSION=1.6.3
              APU_CONFIG="--with-crypto --with-ldap"
              TEST_MALLOC=1
              TEST_LDAP=1
              TEST_ARGS="-defines LDAP"
              TESTS="t/modules/"
          # -------------------------------------------------------------------------
   
    runs-on: self-hosted
    timeout-minutes: 30
    env:
      NOTEST_CFLAGS: ${{ matrix.notest-cflags }}
      CONFIG: ${{ matrix.config }}
    name: ${{ matrix.name }}
    steps:
    - name: Set environment variables
      run: |
        echo "${{ matrix.env }}" >> $GITHUB_ENV
        echo JOBID=`echo "${{ matrix.notest-cflags }} ${{ matrix.env }} ${{ matrix.config }}'"| md5sum - | sed 's/ .*//'` >> $GITHUB_ENV
    # https://github.com/actions/runner-images/issues/9491#issuecomment-1989718917
    #- name: Workaround ASAN issue in Ubuntu 22.04
    # run: sudo sysctl vm.mmap_rnd_bits=28
    - name: apt refresh
      run: sudo apt-get -o Acquire::Retries=5 update
    - name: Install prerequisites
      run: sudo apt-get install -y -o Acquire::Retries=5
                    cpanminus openssl libssl-dev docker.io zlib1g-dev subversion gcc bison flex docker-buildx net-tools libtool-bin libapr1-dev libaprutil1-dev
                    liblua5.3-dev libbrotli-dev libcurl4-openssl-dev     
                    libnghttp2-dev libjansson-dev libpcre2-dev gdb
                    perl-doc ${{ matrix.pkgs }}
    - uses: actions/checkout@v4
    - name: Cache installed libraries
      uses: actions/cache@v4
      with:
        path: ~/root
        key: cache-libs-${{ env.JOBID }}
    - name: Cache CPAN modules
      uses: actions/cache@v4
      with:
        path: ~/perl5
        key: cache-cpan-${{ env.JOBID }}
    - name: Configure environment
      run: ./test/travis_before_linux.sh
      timeout-minutes: 15
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: config.log-${{ env.JOBID }}
        path: |
          /home/runner/build/**/config.log
    - name: Build and test
      run: ./test/travis_run_linux.sh
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: error_log-${{ env.JOBID }}
        path: test/perl-framework/t/logs/error_log

